const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const run = new Function('$input',fs.readFileSync(path.join(__dirname,'waha-input.js'),'utf8'));
const base = {event:'message',session:'default',payload:{id:'false_5500000000000@c.us_TEST01',from:'5500000000000@c.us',fromMe:false,body:'Quero toalhas'}};
const check = (change={}) => {const event=structuredClone(base);Object.assign(event.payload,change);return run({all:()=>[{json:{body:event}}]});};
const good=check()[0].json;
assert.equal(good.message,'Quero toalhas');
assert.equal(check({body:'Qual o horario do cafe?'})[0].json.message,'Qual o horario do cafe?');
assert.equal(check({body:'[AURA TESTE] Quero toalhas'})[0].json.message,'Quero toalhas');
assert.match(good.session_id,/^[a-zA-Z0-9_-]{1,80}$/);
for(const change of [{fromMe:true},{fromMe:undefined},{from:'123456@g.us'},{from:'status@broadcast'},{hasMedia:true}]) assert.deepEqual(check(change),[]);
for(const change of [{id:''},{body:'[AURA TESTE] '},{body:'[AURA TESTE] '+'x'.repeat(2001)}]) assert.throws(()=>check(change));
for(const change of [{event:'message.any'},{session:'other'}]) assert.deepEqual(run({all:()=>[{json:{...base,...change}}]}),[]);
assert.equal(check({from:'5500000000000@lid'}).length,1);
const hash=v=>crypto.createHash('sha256').update(v).digest('hex');
assert.equal(hash(good.request_id),hash(check()[0].json.request_id));
assert.notEqual(hash(good.request_id),hash(check({id:'different'})[0].json.request_id));
assert.match(hash(good.request_id),/^[a-f0-9]{64}$/);
console.log('WAHA: filtros, validacao e idempotencia passaram.');

const namedRun = new Function('$input',fs.readFileSync(path.join(__dirname,'waha-input.js'),'utf8').replace("const expectedSession = 'default';", 'const expectedSession = "Lume";'));
assert.equal(namedRun({all:()=>[{json:{...base,session:'Lume'}}]}).length,1);
assert.deepEqual(namedRun({all:()=>[{json:base}]}),[]);
console.log('Sessao nomeada aceita; outra sessao bloqueada.');
