/* Reception conversation tools. Drafts remain in the dialog during queue polling. */
(()=>{
 const dialog=document.createElement('dialog');dialog.id='conversation-dialog';
 dialog.style.cssText='width:min(760px,95vw);max-height:90vh;overflow:auto;border:1px solid #acbdb6;border-radius:12px';
 dialog.innerHTML='<h2>Conversa do atendimento</h2><p id="conversation-state"></p><div id="conversation-log" role="log" style="max-height:40vh;overflow:auto"></div><label>Mensagem da equipe<textarea id="staff-text" maxlength="2000" style="display:block;width:100%;min-height:100px;font:inherit"></textarea></label><p><button id="takeover">Assumir conversa</button> <button id="release-bot">Devolver à Hostess</button> <button id="notify-start">Avisar início</button></p><p><button id="staff-send">Enviar mensagem</button> <button id="thread-refresh">Atualizar conversa</button> <button id="thread-close">Fechar</button></p><p id="thread-feedback" role="status"></p>';
 document.body.append(dialog);
 const el=id=>document.getElementById(id);let selected=null,busy=false,pending=null;
 async function call(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await r.json();if(!r.ok)throw Error(data.error||'Falha no atendimento');return data}
 function controls(){const own=selected?.status==='in_progress'&&selected?.operator===document.getElementById('operator').value;for(const id of ['takeover','release-bot','notify-start','staff-send'])el(id).disabled=busy||!own;el('thread-refresh').disabled=busy;el('thread-close').disabled=busy;el('staff-text').disabled=busy;el('conversation-state').textContent=selected?.human_operator?'Conversa com '+selected.human_operator+'. Respostas automáticas pausadas.':'Hostess ativa. Assuma o atendimento na fila para responder.'}
 async function load(){const [items,rows]=await Promise.all([call('/api/handoffs/thread/'+encodeURIComponent(selected.id)),call('/api/handoffs')]);selected=rows.find(r=>r.id===selected.id)||selected;el('conversation-log').replaceChildren();for(const item of items){const p=document.createElement('p');p.className='bubble';p.textContent=(item.role==='guest'?'Hóspede':item.role==='staff'?'Equipe ('+item.operator+')':'Hostess')+': '+item.text;el('conversation-log').append(p)}controls();el('conversation-log').scrollTop=el('conversation-log').scrollHeight}
 async function action(name){if(busy)return;busy=true;controls();el('thread-feedback').textContent='';try{const body={id:selected.id,action:name};if(name==='message'){const text=el('staff-text').value.trim();if(!text)throw Error('Escreva uma mensagem.');if(!pending||pending.text!==text)pending={text,request_id:'staff-'+crypto.randomUUID()};Object.assign(body,pending)}const result=await call('/api/handoffs/conversation',body);const labels={sent:'Mensagem aceita pelo WhatsApp.',unknown:'Envio não confirmado. Confira a conversa; não repita o envio.',sending:'Envio em andamento.',local_only:'Mensagem registrada no painel local.'};el('thread-feedback').textContent=labels[result.delivery_status]||(name==='takeover'?'Conversa assumida. Hostess pausada.':'Hostess liberada.');if(name==='message'){el('staff-text').value='';pending=null}await load()}catch(error){el('thread-feedback').textContent=error.message}finally{busy=false;controls()}}
 el('takeover').onclick=()=>action('takeover');el('release-bot').onclick=()=>action('release');el('notify-start').onclick=()=>action('notify_start');el('staff-send').onclick=()=>action('message');el('thread-refresh').onclick=()=>load().catch(e=>el('thread-feedback').textContent=e.message);el('thread-close').onclick=()=>dialog.close();dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault()});
 window.guestUI={
  card(card,row){
   const info=document.createElement('p');const s=row.service;info.textContent=s?(s.reservation_id?'Hospedagem vinculada · Acomodação '+(s.room||'a conferir'):'Hospedagem a conferir')+(s.kind==='toalhas'?' · Toalhas: '+(s.quantity||'quantidade a confirmar'):'')+(s.guest_feedback==='received'?' · Hóspede confirmou recebimento':s.guest_feedback==='not_received'?' · Hóspede informou que não recebeu':s.guest_feedback==='cancelled'?' · Cancelado pelo hóspede antes do atendimento':''):'';
   card.append(info);if(row.status==='open'&&row.waiting_minutes>=15){const waiting=document.createElement('p');waiting.textContent='Aguardando há '+row.waiting_minutes+' minutos.';waiting.style.color='#9b2424';card.append(waiting)}
   const b=document.createElement('button');b.textContent='Ver conversa';b.style.margin='8px';b.onclick=async()=>{selected=row;el('staff-text').value='';pending=null;el('thread-feedback').textContent='';dialog.showModal();try{await load()}catch(e){el('thread-feedback').textContent=e.message}};card.append(b);
  },
  async metrics(){let box=el('experience-metrics');if(!box){box=document.createElement('div');box.id='experience-metrics';box.className='notice';document.getElementById('tickets').before(box)}try{const m=await call('/api/experience');box.replaceChildren();const p=document.createElement('p');p.textContent='Abertos: '+(m.counts.open||0)+' · Em atendimento: '+(m.counts.in_progress||0)+' · Concluídos pela equipe: '+(m.counts.resolved||0)+' · Cancelados antes do atendimento: '+(m.counts.cancelled||0)+' · Recebimentos confirmados: '+(m.feedback.received||0)+' · Espera acima de 15 min: '+m.waiting_over_15_minutes+' · Envios a conferir: '+m.delivery_attention+' · Média até assumir: '+(m.mean_first_service_minutes===null?'sem dados':m.mean_first_service_minutes+' min');box.append(p);if(m.knowledge_gaps.length){const d=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Perguntas sem resposta segura (últimas '+m.sample_limit+' mensagens)';d.append(summary);for(const q of m.knowledge_gaps){const item=document.createElement('p');item.textContent=q;d.append(item)}box.append(d)}}catch(e){box.textContent='Indicadores indisponíveis: '+e.message}}
 };
})();
